# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    telegram_token: '%env(TELEGRAM_BOT_TOKEN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Создаем алиас: когда Symfony видит ClientInterface, она отдает клиент 'default'
    Predis\ClientInterface: '@snc_redis.default'

    # ЖЕСТКАЯ ПРИВЯЗКА ДЛЯ РЕГИСТРАЦИИ:
    App\System\Controller\Api\RegistrationController:
        arguments:
            # Символ @ говорит Symfony: "Возьми именно этот готовый сервис"
            $registrationLoginLimiter: '@limiter.registration_login'


    App\MessageHandler\SendMessageHandler:
        arguments:
            $tgToken: '%telegram_token%'


    App\Service\AI\AiModelInterface: '@App\Service\AI\ProxyApiService'

    App\Service\AI\DeepSeekService:
        arguments:
            $deepseekApiKey: '%env(DEEPSEEK_API_KEY)%'

    App\Service\AI\GigaChatService:
        arguments:
            $gigaChatAuthKey: '%env(GIGACHAT_API_KEY)%'

    App\Service\AI\YandexGptService:
        arguments:
            $yandexApiKey: '%env(YANDEX_API_KEY)%'
            $yandexFolderId: '%env(YANDEX_FOLDER_ID)%'

    App\Service\AI\ProxyApiService:
        arguments:
            $proxyApiKey: '%env(PROXY_API_KEY)%'

    App\Service\AI\OpenAiService:
        arguments:
            $openAiKey: '%env(OPENAI_API_KEY)%'


    # Автоматически помечаем все классы, реализующие MessengerInterface
    _instanceof:
        App\Service\Messenger\MessengerInterface:
            tags: ['app.messenger']

    # Настройка фабрики: она соберет все помеченные сервисы в итератор
    App\Service\Messenger\MessengerFactory:
        arguments: [!tagged_iterator app.messenger]

    # Если в TelegramService нужен специфический HttpClient (опционально)
    App\Service\Messenger\TelegramService:
        autowire: true
