name: sentry_prod

services:

  # 2. Redis
  glitchtip_redis:
    image: redis:6-alpine
    container_name: orion_redis_prod
    restart: always
    networks:
      - app_network

  # Основной веб-интерфейс - аналог Sentry
  glitchtip:
    image: glitchtip/glitchtip
    container_name: orion_glitchtip
    restart: always
    environment: &default-env
      - DATABASE_URL=postgres://${GL_DB_USER}:${GL_DB_PASSWORD}@orion_glitchtip_db:5432/${GL_DB_NAME}
      - REDIS_URL=redis://orion_redis_prod:6379/1
      - SECRET_KEY=${APP_SECRET}
      - GLITCHTIP_DOMAIN=https://sentry.orioncode.ru
      - ALLOWED_HOSTS=sentry.orioncode.ru,glitchtip
      - CSRF_TRUSTED_ORIGINS=https://sentry.orioncode.ru
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - DEFAULT_FROM_EMAIL=admin@orioncode.ru
      - ENABLE_USER_REGISTRATION=True
    depends_on:
      - glitchtip_db
      - glitchtip_redis
    networks:
      - app_network

  # База специально для GlitchTip
  glitchtip_db:
    image: postgres:15-alpine
    container_name: orion_glitchtip_db
    environment:
      POSTGRES_DB: ${GL_DB_NAME}
      POSTGRES_USER: ${GL_DB_USER}
      POSTGRES_PASSWORD: ${GL_DB_PASSWORD}
    volumes:
      - glitchtip_db_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Воркер — он "переваривает" приходящие ошибки от Sentry
  glitchtip_worker:
    image: glitchtip/glitchtip
    container_name: orion_glitchtip_worker
    command: ./bin/run-celery-with-beat.sh
    restart: always
    environment:
      - DATABASE_URL=postgres://${GL_DB_USER}:${GL_DB_PASSWORD}@glitchtip_db:5432/${GL_DB_NAME}
      - REDIS_URL=redis://orion_redis_prod:6379/1
      - SECRET_KEY=${APP_SECRET}
      - GLITCHTIP_DOMAIN=https://sentry.orioncode.ru
      - CSRF_TRUSTED_ORIGINS=https://sentry.orioncode.ru
      - CELERY_QUEUES=default,ingest,billing,cleanup
    depends_on:
      - glitchtip
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  glitchtip_db_data:
